// Generated by CoffeeScript 1.7.1
(function() {
  this.c = function(val) {
    document.getElementById("d").value = val;
  };

  this.v = function(val) {
    document.getElementById("d").value += val;
  };

  this.e = function() {
    var e;
    try {
      c(eval_(document.getElementById("d").value));
    } catch (_error) {
      e = _error;
      c("Error");
    }
  };

}).call(this);
